name: flutter_package_gaw_ui
description: A UI Package for the Get-a-Wash application stack.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.7.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  themed: ^5.0.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  google_fonts: ^5.1.0
  toggle_switch: ^2.1.0
  syncfusion_flutter_datepicker: ^23.1.36
  syncfusion_flutter_charts: ^23.1.36
  smooth_page_indicator: ^1.1.0
  easy_localization: ^3.0.2

  # Get-a-Wash

  flutter_package_gaw_api:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_api
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


dependency_overrides:
  flutter_package_gaw_api:
    path: ../flutter_package_gaw_api


flutter:
  assets:
    - assets/images/core/
    - assets/images/map/
    - assets/icons/pixel_perfect/Bold/SVG/UI Basic/
    - assets/icons/pixel_perfect/Medium/SVG/UI Basic/
    - assets/icons/pixel_perfect/Normal/SVG/UI Basic/
    - assets/icons/pixel_perfect/Bold/SVG/Arrows/
    - assets/icons/pixel_perfect/Medium/SVG/Arrows/
    - assets/icons/pixel_perfect/Normal/SVG/Arrows/
    - assets/icons/custom/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Variable.ttf
        - asset: assets/fonts/GeneralSans-VariableItalic.ttf
