name: gaw_ui
description: A UI Package for the Get-a-Wash application stack.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  syncfusion_flutter_datepicker: ^24.0.0
  syncfusion_flutter_charts: ^24.0.0
  widget_to_marker: ^1.0.4
  smooth_page_indicator: ^1.1.0
  carousel_indicator: ^1.0.6
  fl_chart: 0.66.0
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  beamer: ^1.5.6
  themed: ^5.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.0.0
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.3.10
  freezed: ^2.4.1
  http: ^1.2.0
  tuple: ^2.0.2
  google_maps_flutter: ^2.5.0
  google_map_polyline_new: ^0.3.0+2
  lottie: ^3.0.0
  multi_dropdown: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/core/
    - assets/images/map/
    - assets/images/banner/
    - assets/icons/pixel_perfect/Bold/SVG/UI Basic/
    - assets/icons/pixel_perfect/Medium/SVG/UI Basic/
    - assets/icons/pixel_perfect/Normal/SVG/UI Basic/
    - assets/icons/pixel_perfect/Bold/SVG/Arrows/
    - assets/icons/pixel_perfect/Medium/SVG/Arrows/
    - assets/icons/pixel_perfect/Normal/SVG/Arrows/
    - assets/icons/custom/
    - assets/videos/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Variable.ttf
        - asset: assets/fonts/GeneralSans-VariableItalic.ttf
